### ISSUE TITLE
Strange Errors 

### ISSUE THREAD

**Issue by smiths** [pjmc-oliveira/HubListener#109] opened 2019-03-29 14:42 UTC
```
> hub-listener@1.0.0 start /Users/smiths/Repos/StdntWork/HubListener/src
> node index.js

listening on 8080
2019-03-29 10:36:43.695 [index.js] INFO: [POST] request to /analyse
2019-03-29 10:36:43.707 [clone.js] DEBUG: Initializing repository Clone from: 'https://github.com/pjmc-oliveira/HubListener'
2019-03-29 10:36:43.708 [clone.js] DEBUG: clonePath not passed, creating from URL
2019-03-29 10:36:43.708 [clone.js] DEBUG: Clone directory found at: '/Users/smiths/Repos/StdntWork/HubListener/src/repos/pjmc-oliveira/HubListener'
2019-03-29 10:36:43.708 [clone.js] DEBUG: Pulling latest changes...
2019-03-29 10:36:43.712 [clone.js] DEBUG: Changes successfuly pulled!
(node:49299) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:485:3)
    at new ClientRequest (_http_client.js:206:14)
    at request (https.js:301:10)
    at /Users/smiths/Repos/StdntWork/HubListener/src/node_modules/node-fetch/index.js:119:13
    at new Promise (<anonymous>)
    at new Fetch (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/node-fetch/index.js:37:10)
    at module.exports (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at Object.query (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/graphql-client/index.js:54:14)
    at Client.query (/Users/smiths/Repos/StdntWork/HubListener/src/client.js:61:28)
(node:49299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:49299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:49299) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_CHAR]: Invalid character in header content ["authorization"]
    at ClientRequest.setHeader (_http_outgoing.js:485:3)
    at new ClientRequest (_http_client.js:206:14)
    at request (https.js:301:10)
    at /Users/smiths/Repos/StdntWork/HubListener/src/node_modules/node-fetch/index.js:119:13
    at new Promise (<anonymous>)
    at new Fetch (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/node-fetch/index.js:49:9)
    at Fetch (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/node-fetch/index.js:37:10)
    at module.exports (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/isomorphic-fetch/fetch-npm-node.js:8:19)
    at Object.query (/Users/smiths/Repos/StdntWork/HubListener/src/node_modules/graphql-client/index.js:54:14)
    at Client.query (/Users/smiths/Repos/StdntWork/HubListener/src/client.js:61:28)
(node:49299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
^C
'''

**Comment by ahmadzed** [comment] 2019-03-29 15:47
The issue is caused by having a line break in `auth_token.txt`.  

It is totally reasonable to have an empty line following the token in the file, so this issue has been fixed by trimming the file contents.

**Closed by ahmadzed** 2019-03-29 15:47 UTC
Labels: bug
